{
 "title": "emqx-test",
 "tags": [ "test" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(up, cluster)" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emqx_cluster_status{cluster=\"$cluster\"}",
     "legendFormat": "Status",
     "query": "emqx_cluster_status{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "License",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(emqx_license_remaining_days{cluster=\"$cluster\"})",
     "legendFormat": "Days Remaining",
     "query": "sum(emqx_license_remaining_days{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(emqx_license_expiration_time{cluster=\"$cluster\"})",
     "legendFormat": "Expiry At",
     "query": "sum(emqx_license_expiration_time{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})",
     "legendFormat": "Max Conns",
     "query": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Connections",
     "query": "sum(emqx_connections_count{instance=~\".*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_messages_input_period_second{cluster=\"$cluster\"}",
     "legendFormat": "Msg Input Period Second",
     "query": "emqx_messages_input_period_second{cluster=\"$cluster\"}"
    },
    {
     "expr": "emqx_messages_output_period_second{cluster=\"$cluster\"}",
     "legendFormat": "Msg Output Period Second",
     "query": "emqx_messages_output_period_second{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Nodes Running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(emqx_cluster_nodes_running{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Running",
     "query": "max(emqx_cluster_nodes_running{instance=~\".*\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max(emqx_cluster_nodes_stopped{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Stopped",
     "query": "max(emqx_cluster_nodes_stopped{instance=~\".*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Exporter Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(emqx_scrape_collector_duration_seconds{cluster=\"$cluster\"})",
     "legendFormat": "Latency",
     "query": "sum(emqx_scrape_collector_duration_seconds{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_live_connections_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Total",
     "query": "sum(emqx_live_connections_count{instance=~\".*\", cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by(instance) (emqx_connections_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}",
     "query": "sum by(instance) (emqx_connections_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Subscriptions",
     "query": "sum(emqx_suboptions_count{instance=~\".*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_sessions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Count",
     "query": "sum(emqx_sessions_count{instance=~\".*\", cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})",
     "legendFormat": "Max",
     "query": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Rule Engine Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{ rule }}",
     "query": "sum by(rule) (emqx_rule_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Connect Auth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval])) - sum(irate(emqx_packets_connack_error {instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Auth Success",
     "query": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval])) - sum(irate(emqx_packets_connack_error {instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(irate(emqx_packets_connack_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Auth Failure",
     "query": "sum(irate(emqx_packets_connack_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "ACL Auth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_publish_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Publish ACL Failure",
     "query": "sum(irate(emqx_packets_publish_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(irate(emqx_packets_subscribe_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sub ACL Failure ",
     "query": "sum(irate(emqx_packets_subscribe_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data Bridge Queuing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type, name) (emqx_rule_bridge_queuing{cluster=\"$cluster\"})",
     "legendFormat": "{{type}}-{{name}}",
     "query": "sum by(type, name) (emqx_rule_bridge_queuing{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Rule Engine Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{ rule }}",
     "query": "sum by(rule) (emqx_rule_exec_rate{cluster=\"$cluster\", node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Rule Engine Exec Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}",
     "query": "sum by(rule) (irate(emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Rule Engine Exec Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}",
     "query": "sum by(rule) (irate(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Rule Engine Action Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}",
     "query": "sum by(rule) (irate(emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Rule Engine Action Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}",
     "query": "sum by(rule) (irate(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Connection Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_client_connected{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Connections",
       "query": "sum(irate(emqx_client_connected{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_client_disconnected{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Disconnections",
       "query": "sum(irate(emqx_client_disconnected{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Client Sub Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_client_subscribe{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "Subscribes",
       "query": "sum(irate(emqx_client_subscribe{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_client_unsubscribe{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "Unsubscribes",
       "query": "sum(irate(emqx_client_unsubscribe{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Client Connect Auth Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_client_authenticate{cluster=\"$cluster\",instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "Connect Auth",
       "query": "sum(irate(emqx_client_authenticate{cluster=\"$cluster\",instance=~\".*\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_client_auth_anonymous{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "Anonymous Auth",
       "query": "sum(irate(emqx_client_auth_anonymous{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Client ACL Auth Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_client_authorize{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "ACL Auth",
       "query": "sum(irate(emqx_client_authorize{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Packets Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Connect",
       "query": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_connack_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Connack Sent",
       "query": "sum(irate(emqx_packets_connack_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_connack_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Connack Error",
       "query": "sum(irate(emqx_packets_connack_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Packets Disconnections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_disconnect_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Disconnect Sent",
       "query": "sum(irate(emqx_packets_disconnect_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_disconnect_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Disconnect Received",
       "query": "sum(irate(emqx_packets_disconnect_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Packets Publish",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_publish_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Sent",
       "query": "sum(irate(emqx_packets_publish_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_publish_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Received",
       "query": "sum(irate(emqx_packets_publish_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_publish_dropped{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Dropped",
       "query": "sum(irate(emqx_packets_publish_dropped{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_publish_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Error",
       "query": "sum(irate(emqx_packets_publish_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Packets Subscribe/Unsubscribe",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_subscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Subscribe Received",
       "query": "sum(irate(emqx_packets_subscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_suback_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Suback Sent",
       "query": "sum(irate(emqx_packets_suback_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_subscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Subscribe Error",
       "query": "sum(irate(emqx_packets_subscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_unsubscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Unsubscribe Received",
       "query": "sum(irate(emqx_packets_unsubscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_packets_unsubscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Unsubscribe Error",
       "query": "sum(irate(emqx_packets_unsubscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Messages Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_messages_received{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Messages Received",
       "query": "sum(irate(emqx_messages_received{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_messages_sent{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Messages Sent",
       "query": "sum(irate(emqx_messages_sent{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_messages_dropped{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Messages Dropped",
       "query": "sum(irate(emqx_messages_dropped{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Messages QOS Received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_messages_qos0_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "QOS0",
       "query": "sum(irate(emqx_messages_qos0_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_messages_qos1_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "QOS1",
       "query": "sum(irate(emqx_messages_qos1_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_messages_qos2_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
       "legendFormat": "QOS2",
       "query": "sum(irate(emqx_messages_qos2_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Cluster Traffic Statistics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(emqx_bytes_received{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Bytes received",
       "query": "sum(irate(emqx_bytes_received{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))"
      },
      {
       "expr": "sum(irate(emqx_bytes_sent{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Bytes sent",
       "query": "sum(irate(emqx_bytes_sent{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Rule Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data Bridge Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by(type, name) (emqx_rule_bridge_status{cluster=\"$cluster\"})",
       "legendFormat": "Status",
       "query": "sum by(type, name) (emqx_rule_bridge_status{cluster=\"$cluster\"})"
      },
      {
       "expr": "sum by(type, name) (emqx_rule_bridge_queuing{cluster=\"$cluster\"})",
       "legendFormat": "Queuing",
       "query": "sum by(type, name) (emqx_rule_bridge_queuing{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Rule Engine Execute Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 33 },
     "targets": [
      {
       "expr": "sum by(rule) (emqx_rule_topic_hit_count{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "Topic Hit Cout",
       "query": "sum by(rule) (emqx_rule_topic_hit_count{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "max by(rule) (emqx_rule_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "Max Rate",
       "query": "max by(rule) (emqx_rule_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(rule) (emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "Exec Pass",
       "query": "sum by(rule) (emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(rule) (irate(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
       "legendFormat": "Exec Failure last 15m",
       "query": "sum by(rule) (irate(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[15m]))"
      },
      {
       "expr": "sum by(rule) (emqx_rule_exec_no_result_count{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "Exec No Result",
       "query": "sum by(rule) (emqx_rule_exec_no_result_count{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(rule) (emqx_rule_action_total{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "Action Total",
       "query": "sum by(rule) (emqx_rule_action_total{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(rule) (emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "Action Success",
       "query": "sum by(rule) (emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(rule) (increase(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[15m]))",
       "legendFormat": "Action Failed last 15m",
       "query": "sum by(rule) (increase(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[15m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Connect Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Authenticate Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by(resource) (emqx_authentication_resource_status{cluster=\"$cluster\"})",
       "legendFormat": "AuthN Status",
       "query": "sum by(resource) (emqx_authentication_resource_status{cluster=\"$cluster\"})"
      },
      {
       "expr": "max by(resource) (emqx_authentication_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "AuthN Max Rate",
       "query": "max by(resource) (emqx_authentication_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(resource) (emqx_authentication_total{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "AuthN Total",
       "query": "sum by(resource) (emqx_authentication_total{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(resource) (emqx_authentication_allow_count{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "AuthN Allow",
       "query": "sum by(resource) (emqx_authentication_allow_count{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(resource) (irate(emqx_authentication_deny_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
       "legendFormat": "AuthN Deny last 15m",
       "query": "sum by(resource) (irate(emqx_authentication_deny_count{cluster=\"$cluster\", node=~\".*\"}[15m]))"
      }
     ]
    },
    {
     "title": "Authenticate Current Exec Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(resource) (emqx_authentication_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "{{resource}}",
       "query": "sum by(resource) (emqx_authentication_exec_rate{cluster=\"$cluster\", node=~\".*\"})"
      }
     ]
    },
    {
     "title": "Authenticate Last 5m Exec Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(resource) (emqx_authentication_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "{{resource}}",
       "query": "sum by(resource) (emqx_authentication_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "ACL Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Authorize Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by(resource) (emqx_authorization_resource_status{cluster=\"$cluster\"})",
       "legendFormat": "AuthZ Status",
       "query": "sum by(resource) (emqx_authorization_resource_status{cluster=\"$cluster\"})"
      },
      {
       "expr": "max by(resource) (emqx_authorization_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "AuthZ Max Rate",
       "query": "max by(resource) (emqx_authorization_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(resource) (emqx_authorization_total{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "AuthZ Total",
       "query": "sum by(resource) (emqx_authorization_total{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(resource) (emqx_authorization_allow_count{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "AuthZ Allow",
       "query": "sum by(resource) (emqx_authorization_allow_count{cluster=\"$cluster\", node=~\".*\"})"
      },
      {
       "expr": "sum by(resource) (irate(emqx_authorization_deny_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
       "legendFormat": "AuthZ Deny last 15m",
       "query": "sum by(resource) (irate(emqx_authorization_deny_count{cluster=\"$cluster\", node=~\".*\"}[15m]))"
      }
     ]
    },
    {
     "title": "Authorize Current Exec Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(resource) (emqx_authorization_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "{{resource}}",
       "query": "sum by(resource) (emqx_authorization_exec_rate{cluster=\"$cluster\", node=~\".*\"})"
      }
     ]
    },
    {
     "title": "Authorize Last 5m Exec Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(resource) (emqx_authorization_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
       "legendFormat": "{{resource}}",
       "query": "sum by(resource) (emqx_authorization_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Last 1m CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load1\"})",
       "legendFormat": "{{node}}",
       "query": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load1\"})"
      }
     ]
    },
    {
     "title": "Last 5m CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load5\"})",
       "legendFormat": "{{node}}",
       "query": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load5\"})"
      }
     ]
    },
    {
     "title": "Last 15m CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load15\"})",
       "legendFormat": "{{node}}",
       "query": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load15\"})"
      }
     ]
    }
   ]
  }
 ]
}